# Generated by Django 3.2 on 2021-05-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ica_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('ica_image', models.FileField(upload_to='ica/')),
            ],
        ),
    ]
