# Generated by Django 3.2 on 2021-05-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0002_ica_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEG_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('egg_mne', models.FileField(upload_to='eeg/')),
                ('egg_mne_filter', models.FileField(upload_to='eeg_filter/')),
            ],
        ),
    ]
