# Generated by Django 3.2 on 2021-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0003_eeg_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EEG_filter',
        ),
        migrations.AddField(
            model_name='ica_image',
            name='egg_mne',
            field=models.FileField(blank=True, null=True, upload_to='eeg/'),
        ),
        migrations.AddField(
            model_name='ica_image',
            name='egg_mne_filter',
            field=models.FileField(blank=True, null=True, upload_to='eeg_filter/'),
        ),
    ]
