# Generated by Django 3.2 on 2021-05-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0004_auto_20210514_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='ica_image',
            name='psd',
            field=models.FileField(blank=True, null=True, upload_to='psd/'),
        ),
        migrations.AddField(
            model_name='ica_image',
            name='sensors',
            field=models.FileField(blank=True, null=True, upload_to='sensors/'),
        ),
    ]
