# Generated by Django 3.2 on 2021-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0005_auto_20210514_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='ica_image',
            name='cz_propertie',
            field=models.FileField(blank=True, null=True, upload_to='cz_properties/'),
        ),
    ]
