# Generated by Django 3.2 on 2021-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0009_edf_saveby'),
    ]

    operations = [
        migrations.AddField(
            model_name='edf',
            name='cz_propertie',
            field=models.FileField(blank=True, null=True, upload_to='cz_properties/'),
        ),
        migrations.AddField(
            model_name='edf',
            name='egg_mne',
            field=models.FileField(blank=True, null=True, upload_to='eeg/'),
        ),
        migrations.AddField(
            model_name='edf',
            name='egg_mne_filter',
            field=models.FileField(blank=True, null=True, upload_to='eeg_filter/'),
        ),
        migrations.AddField(
            model_name='edf',
            name='ica_image',
            field=models.FileField(blank=True, null=True, upload_to='ica/'),
        ),
        migrations.AddField(
            model_name='edf',
            name='psd',
            field=models.FileField(blank=True, null=True, upload_to='psd/'),
        ),
        migrations.AddField(
            model_name='edf',
            name='sensors',
            field=models.FileField(blank=True, null=True, upload_to='sensors/'),
        ),
        migrations.AlterField(
            model_name='edf',
            name='edf',
            field=models.FileField(blank=True, null=True, upload_to='edfs/'),
        ),
    ]
