# Generated by Django 3.2 on 2021-05-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0010_auto_20210515_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edf',
            name='cz_propertie',
        ),
        migrations.RemoveField(
            model_name='edf',
            name='egg_mne',
        ),
        migrations.RemoveField(
            model_name='edf',
            name='egg_mne_filter',
        ),
        migrations.RemoveField(
            model_name='edf',
            name='ica_image',
        ),
        migrations.RemoveField(
            model_name='edf',
            name='psd',
        ),
        migrations.RemoveField(
            model_name='edf',
            name='sensors',
        ),
        migrations.AddField(
            model_name='ica_image',
            name='edf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateform.edf'),
        ),
    ]
