# Generated by Django 3.2 on 2021-05-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0011_auto_20210515_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ica_image',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='ica_image',
            name='patient',
        ),
    ]
