# Generated by Django 3.2 on 2021-05-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0012_auto_20210515_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='edf',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
