# Generated by Django 3.2 on 2021-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0013_edf_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ica_image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
