# Generated by Django 3.2 on 2021-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0016_edf_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edf',
            name='decision',
            field=models.CharField(choices=[('epileptic', 'Epileptic'), ('no_Epileptic', 'No Epileptic')], max_length=100, null=True),
        ),
    ]
