# Generated by Django 3.2 on 2021-05-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0017_alter_edf_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edf',
            name='decision',
            field=models.CharField(choices=[('epilepsy', 'Epileptic'), ('no_epilepsy', 'No Epileptic')], max_length=100, null=True),
        ),
    ]
